# Generated by Django 4.1.4 on 2022-12-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ip',
            new_name='IpData',
        ),
    ]
